[package]
name = "segment-chess-board"
version = "0.1.0"
authors = ["Chase Starr <chasestarr@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
imageproc = "0.22.0"
chfft = "0.3.4"
